export const UserStatusActionTypes = {
    SET_CURRENT_USER_STATUS: "SET_CURRENT_USER_STATUS",
    SET_CURRENT_USER_IS_LOGGED_IN: "SET_CURRENT_USER_IS_LOGGED_IN",
    SET_CURRENT_USER_IS_ADMIN: "SET_CURRENT_USER_IS_ADMIN",
    SET_CURRENT_USER_ALL_STATUS: "SET_CURRENT_USER_ALL_STATUS",
};
