export const ROUTER_LINKS = {
    home: "/",
    search: "/search",
    basket: "/basket",
    item: "/item/",
    navigation: "/navigation",
    orders: "/orders",
    signIn: "/signIn",
    signUp: "/signUp",
    profile: "/profile",
    searchResult: "/searchResult/",
    addProduct: "/addProduct",
    deleteProduct: "/deleteProduct",
    addBanner: "/addBanner",
    addOnSale: "/addOnSale",
};
